vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1 
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.cursorline = true
vim.g.mapleader = " " 
